# Este archivo configura el analizador, que analiza estáticamente el código Dart
# para verificar errores, advertencias y lints.
#
# Los problemas identificados por el analizador se muestran en la interfaz de usuario
# de los IDEs habilitados para Dart. El analizador también se puede invocar desde
# la línea de comandos ejecutando `flutter analyze`.

# La siguiente línea activa un conjunto de lints recomendados para aplicaciones Flutter,
# paquetes y plugins diseñados para fomentar buenas prácticas de codificación.
include: package:flutter_lints/flutter.yaml

linter:
  # Las reglas de lint aplicadas a este proyecto se pueden personalizar en la
  # sección a continuación para deshabilitar reglas de `package:flutter_lints/flutter.yaml`
  # o para habilitar reglas adicionales.
  rules:
    # Estilo y formato
    prefer_single_quotes: true        # Usar comillas simples en lugar de dobles
    # require_trailing_commas: false     # Temporalmente deshabilitado
    sort_child_properties_last: true  # Propiedades child al final en widgets
    
    # Buenas prácticas
    avoid_print: true                 # Evitar print() en código de producción
    # prefer_const_constructors: false   # Temporalmente deshabilitado
    prefer_final_locals: true         # Preferir variables locales final
    # avoid_redundant_argument_values: false  # Temporalmente deshabilitado
    
    # Rendimiento
    avoid_unnecessary_containers: true  # Evitar Containers innecesarios
    use_key_in_widget_constructors: true  # Usar key en constructores de widgets
    
    # Accesibilidad
    use_full_hex_values_for_flutter_colors: true  # Usar valores hex completos para colores

analyzer:
  errors:
    # Tratar algunos lints como warnings en lugar de errores
    prefer_const_constructors: warning
    prefer_final_locals: warning
    require_trailing_commas: warning
    avoid_redundant_argument_values: warning
    prefer_const_literals_to_create_immutables: warning
  exclude:
    # Excluir archivos generados automáticamente
    - "**/*.g.dart"
    - "**/*.freezed.dart"

# Información adicional sobre este archivo se puede encontrar en
# https://dart.dev/guides/language/analysis-options
