// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo1HhUvsVEF0aP-mOMZb_DEW6uUr-evlg',
    appId: '1:171343975181:web:44ecf312856962cbf35644',
    messagingSenderId: '171343975181',
    projectId: 'agenda-glam-a20d8',
    authDomain: 'agenda-glam-a20d8.firebaseapp.com',
    storageBucket: 'agenda-glam-a20d8.firebasestorage.app',
    measurementId: 'G-8PJGHEBKD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_WSQDnP2MD9Vd1XHqbO2jRN18wwe5BHs',
    appId: '1:171343975181:android:3dd2e7910bc12efdf35644',
    messagingSenderId: '171343975181',
    projectId: 'agenda-glam-a20d8',
    storageBucket: 'agenda-glam-a20d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXLCVIwzIkqspEvQBh05iqmiVyA5q7_1M',
    appId: '1:171343975181:ios:249d1de59c68225cf35644',
    messagingSenderId: '171343975181',
    projectId: 'agenda-glam-a20d8',
    storageBucket: 'agenda-glam-a20d8.firebasestorage.app',
    iosBundleId: 'com.example.agendaGlam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXLCVIwzIkqspEvQBh05iqmiVyA5q7_1M',
    appId: '1:171343975181:ios:249d1de59c68225cf35644',
    messagingSenderId: '171343975181',
    projectId: 'agenda-glam-a20d8',
    storageBucket: 'agenda-glam-a20d8.firebasestorage.app',
    iosBundleId: 'com.example.agendaGlam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo1HhUvsVEF0aP-mOMZb_DEW6uUr-evlg',
    appId: '1:171343975181:web:228afdae697e9e4bf35644',
    messagingSenderId: '171343975181',
    projectId: 'agenda-glam-a20d8',
    authDomain: 'agenda-glam-a20d8.firebaseapp.com',
    storageBucket: 'agenda-glam-a20d8.firebasestorage.app',
    measurementId: 'G-97YBD7QLE0',
  );
}
